project:
  type: book
  output-dir: docs

book:
  title: "OR in Julia"
  author: "Christian Barz"
  navbar:
    right:
      - icon: github
        href: https://github.com/barz-christian/OR_in_Julia
  chapters:
    - index.qmd
    - setup_and_test.ipynb
    - milp/01_milp_cflp.ipynb
    - sa/02_sa_cflp.ipynb
    - sa/03_sa_cflp_with_heuristics.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css


