project:
  type: book
  output-dir: docs

book:
  title: "OR in Julia"
  author: "Christian Barz"
  navbar:
    right:
      - icon: github
        href: https://github.com/barz-christian/OR_in_Julia
  chapters:
    - index.qmd
    - 01_test_installation.ipynb
    - 02_milp_cflp.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css


